const app = document.querySelector('#app');
const promptSets = [
  ['帮我推荐一款适合军训的防晒霜','推荐一款适合秋冬的香水','通勤耳机怎么选','敏感肌换季怎么护肤','帮我挑一件轻薄羽绒服'],
  ['预算 100 元内的防晒霜','适合油皮的日常乳液','送给朋友的实用礼物','小户型收纳好物','周末露营需要带什么']
];
const products = [
  {brand:'澄野',name:'清透高倍户外防晒乳 50ml',price:'¥69',tags:['自营演示','SPF50+','清爽不黏'],reason:'质地轻，成膜快，适合军训期间频繁补涂。'},
  {brand:'昼屿',name:'水感轻盈防晒霜 40ml',price:'¥52',tags:['示例商品','通勤友好','不泛白'],reason:'肤感更水润，适合日常通勤与不喜欢厚重感的人。'},
  {brand:'山茶实验室',name:'户外防护喷雾 80ml',price:'¥88',tags:['演示数据','防水型','大容量'],reason:'喷雾上身方便，适合军训中需要快速补涂的时刻。'}
];
let state = {screen:'home', promptIndex:0, questionIndex:0, answers:{}, favorites:[], drawer:false};

function productCard(product, compact=false){return `<article class="product-card ${compact?'compact':''}"><div class="product-art"><img src="assets/sunscreen-demo.png" alt="${product.name}演示包装图"></div><div class="product-info"><div class="product-brand">${product.brand} · 演示商品</div><h3>${product.name}</h3><div class="tag-row">${product.tags.map(tag=>`<span class="tag">${tag}</span>`).join('')}</div><div class="price-row"><span class="price">${product.price}</span><button class="heart" data-favorite="${product.name}" aria-label="收藏"><i class="ph ${state.favorites.includes(product.name)?'ph-heart-fill':'ph-heart'}"></i></button></div>${compact?'':`<p class="reason">${product.reason}</p>`}</div></article>`}
function home(){const prompts=promptSets[state.promptIndex]; return `<section class="hero-banner"><div class="hero-kicker">SHIGUANG / 购物决策助手</div><h1>先说你的想法，<br>剩下的交给拾光</h1><p>把选择变成一段有依据的探索。</p></section><div class="section-head"><h2>你可以想问</h2><button class="text-button" id="refreshPrompts">换一批 ↻</button></div><div class="prompt-list">${prompts.map(p=>`<button class="chip" data-prompt="${p}">${p}</button>`).join('')}</div><p class="micro-copy">试试从一个具体场景开始，拾光会继续问你几个关键问题。</p>`}
function flow(){const questions=[{title:'你的肤质或皮肤情况是？',options:['油性 / 混合','中性 / 不确定','干性 / 偏敏感']},{title:'这次防晒霜单件预算大概在哪个范围？',options:['50 元以内','50 - 100 元','100 元以上']},{title:'你更在意哪种使用感？',options:['清爽不黏','防水耐汗','成膜快好补涂']}]; const q=questions[state.questionIndex]; return `<div class="flow-intro"><div class="eyebrow">正在帮你缩小选择范围</div><h1>适合军训的防晒霜</h1><p>先补充一点偏好，结果会更贴近你的真实场景。</p></div><div class="user-bubble">帮我推荐一款适合军训的防晒霜</div><div class="question-card"><h2>${q.title}</h2><div class="question-options">${q.options.map(o=>`<button class="option" data-answer="${o}">${o}</button>`).join('')}</div><form class="free-answer" id="answerForm"><input placeholder="也可以直接告诉我…" aria-label="自定义答案"><button class="small-submit">继续</button></form></div>`}
function thinkingCard(mode='running'){if(mode==='complete'){return `<section class="thinking-card complete-card"><div class="thinking-title"><span class="state-check"><i class="ph ph-check"></i></span><strong>任务完成</strong><button class="collapse-button" aria-label="收起"><i class="ph ph-caret-up"></i></button></div><div class="question-summary"><div><b>你的肤质或皮肤情况是？</b><span>${state.answers.skin||'中性 / 不确定'}</span></div><div><b>这次防晒霜单件预算大概在哪个范围？</b><span>${state.answers.budget||'50 - 100 元'}</span></div><div><b>军训防晒你更看重哪些点？</b><span>${state.answers.feel||'清爽不黏'}</span></div><div><b>对防晒类型有偏好吗？</b><span>化学防晒 / 不确定</span></div></div></section>`}return `<section class="thinking-stack"><div class="thought-done"><span class="state-check pale-check"><i class="ph ph-check"></i></span><span>已完成思考</span></div><div class="thinking-card active-card"><div class="thinking-title"><span class="thinking-pulse"><i class="ph ph-spinner-gap"></i></span><strong>正在执行任务中...</strong><button class="collapse-button" aria-label="展开或收起"><i class="ph ph-caret-up"></i></button></div><div class="task-lines"><div class="task-line done"><span><i class="ph ph-check"></i></span>拾光已完成商品信息收集 <em>（用时3s）</em><i class="ph ph-caret-down task-toggle"></i></div><div class="task-line done"><span><i class="ph ph-check"></i></span>拾光已帮你挑选好商品 <em>（用时2s）</em><i class="ph ph-caret-down task-toggle"></i></div><div class="task-line current"><span><i class="ph ph-spinner-gap"></i></span>拾光正在对比商品价格<i class="ph ph-caret-up task-toggle"></i></div><div class="task-line pending"><span></span>筛选整理<i class="ph ph-caret-down task-toggle"></i></div></div></div></section>`}
function results(){return `<div class="flow-intro"><div class="eyebrow">拾光已完成整理</div><h1>给你的军训防晒建议</h1></div>${thinkingCard('complete')}<div class="summary-box"><h3>这次选择依据</h3><div class="summary-row"><b>肤质</b><span>${state.answers.skin||'中性 / 不确定'}</span></div><div class="summary-row"><b>预算</b><span>${state.answers.budget||'50 - 100 元'}</span></div><div class="summary-row"><b>偏好</b><span>${state.answers.feel||'清爽不黏'}</span></div></div><p class="results-copy">军训场景可以优先查看 SPF50+、PA++++、质地轻的产品。按你的预算与偏好，先从清爽、方便补涂的乳液型开始比较。</p><h2 style="margin:24px 0 5px">军训主推</h2>${productCard(products[0])}<p class="after-card-summary"><strong>整体归纳</strong><br>这款的演示标签与当前偏好比较接近，重点是容量、肤感和购买渠道。实际使用前请以商品详情页、成分表和个人耐受情况为准。</p><div class="tip-box"><strong>使用提醒</strong><span>出门前预留成膜时间，户外活动中按出汗和擦拭情况及时补涂。演示原型不替代专业建议。</span></div><div class="cta-row"><button class="secondary-cta" id="openList"><i class="ph ph-list"></i> 商品列表</button><button class="primary-cta" data-action="favoriteTop">收藏主推</button></div><p class="feedback">这些商品为交互演示数据，价格与库存不代表真实购买信息。</p><h3 style="margin-top:28px">你还可以继续问</h3><div class="prompt-list" style="margin-top:12px"><button class="chip" data-follow="怎样判断防晒是否需要补涂？">怎样判断防晒是否需要补涂？</button><button class="chip" data-follow="可以和什么妆前搭配？">可以和什么妆前搭配？</button></div>`}
function render(){if(state.screen==='home') app.innerHTML=home(); if(state.screen==='flow') app.innerHTML=flow(); if(state.screen==='progress') app.innerHTML=`<div class="flow-intro"><div class="eyebrow">已收到你的偏好</div><h1>正在为你整理合适的防晒霜</h1></div>${thinkingCard('running')}`; if(state.screen==='results') app.innerHTML=results(); bind();}
function bind(){document.querySelector('#refreshPrompts')?.addEventListener('click',()=>{state.promptIndex=(state.promptIndex+1)%promptSets.length;render()});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.prompt.includes('防晒')){state.screen='flow';render()}else showNotice('这个入口暂未展开');}));document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.answer)));document.querySelector('#answerForm')?.addEventListener('submit',e=>{e.preventDefault();const val=e.target.querySelector('input').value.trim();if(val) choose(val)});document.querySelector('#openList')?.addEventListener('click',openList);document.querySelectorAll('[data-follow]').forEach(b=>b.addEventListener('click',()=>{state.screen='flow';state.questionIndex=2;render()}));document.querySelectorAll('[data-favorite]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(b.dataset.favorite)));document.querySelector('[data-action="favoriteTop"]')?.addEventListener('click',()=>toggleFavorite(products[0].name));document.querySelectorAll('[data-action="personal"]').forEach(b=>b.addEventListener('click',()=>{state.screen='flow';state.questionIndex=0;render()}));document.querySelectorAll('[data-action="compare"]').forEach(b=>b.addEventListener('click',showCompare));document.querySelectorAll('[data-history]').forEach(b=>b.addEventListener('click',()=>{closeSide();if(b.dataset.history==='防晒霜'){state.screen='results';render()}else showNotice('这条历史记录是演示占位，可继续追问。')}));}
function showNotice(text){app.innerHTML=`<div class="empty-state"><strong>${text}</strong><span>当前原型先聚焦防晒霜主流程。</span><br><button class="primary-cta" style="margin-top:18px" id="backHome">回到首页</button></div>`;document.querySelector('#backHome').onclick=()=>{state.screen='home';render()}}
function showCompare(){closeSide();showNotice('比价入口已准备好');}
function choose(answer){const keys=['skin','budget','feel'];state.answers[keys[state.questionIndex]]=answer;if(state.questionIndex<2){state.questionIndex++;render()}else{state.screen='progress';render();setTimeout(()=>{state.screen='results';render()},1250)}}
function toggleFavorite(name){if(state.favorites.includes(name))state.favorites=state.favorites.filter(x=>x!==name);else state.favorites.push(name);document.querySelector('#favoriteCount').textContent=state.favorites.length;document.querySelectorAll(`[data-favorite="${name}"]`).forEach(button=>{button.innerHTML=`<i class="ph ${state.favorites.includes(name)?'ph-heart-fill':'ph-heart'}"></i>`})}
function openList(){state.drawer=true;document.querySelector('#scrim').classList.add('open');const drawer=document.createElement('section');drawer.className='product-sheet open';drawer.id='productDrawer';drawer.innerHTML=`<div class="sheet-grabber"></div><div class="side-head"><strong style="font-size:22px">商品列表</strong><button class="close-button" id="closeProducts" aria-label="关闭商品列表"><i class="ph ph-x"></i></button></div><p style="color:var(--muted);font-size:13px">按与你的偏好匹配度排序 · ${products.length} 款演示商品</p><div style="overflow:auto">${products.map(p=>productCard(p,true)).join('')}</div>`;document.querySelector('.phone-shell').appendChild(drawer);document.querySelector('#closeProducts').addEventListener('click',closeList);document.querySelectorAll('#productDrawer [data-favorite]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(b.dataset.favorite)))}
function closeList(){document.querySelector('#productDrawer')?.remove();document.querySelector('#scrim').classList.remove('open');state.drawer=false}
function openSide(){document.querySelector('#sidePanel').classList.add('open');document.querySelector('#scrim').classList.add('open')};function closeSide(){document.querySelector('#sidePanel').classList.remove('open');if(!state.drawer)document.querySelector('#scrim').classList.remove('open')}
document.querySelector('#menuButton').addEventListener('click',openSide);document.querySelector('#closeSide').addEventListener('click',closeSide);document.querySelector('#scrim').addEventListener('click',()=>{closeSide();closeList()});document.querySelector('#homeButton').addEventListener('click',()=>{closeSide();state.screen='home';state.questionIndex=0;render()});document.querySelector('#newChat').addEventListener('click',()=>{closeSide();state.screen='home';state.answers={};state.questionIndex=0;render()});document.querySelector('#historyButton').addEventListener('click',openSide);document.querySelectorAll('[data-side]').forEach(b=>b.addEventListener('click',()=>{closeSide();if(b.dataset.side==='favorites'&&state.favorites.length===0){app.innerHTML='<div class="empty-state"><strong>还没有收藏</strong><span>在商品卡上点一下心形，就会出现在这里。</span></div>'}}));document.querySelector('#composer').addEventListener('submit',e=>{e.preventDefault();const val=document.querySelector('#messageInput').value.trim();if(!val)return;if(val.includes('防晒')){state.screen='flow';document.querySelector('#messageInput').value='';render()}else{document.querySelector('#messageInput').value='';app.innerHTML=`<div class="empty-state"><strong>收到你的问题</strong><span>这是演示原型，当前先聚焦“防晒霜”主流程。</span><br><button class="primary-cta" style="margin-top:18px" id="backHome">回到首页</button></div>`;document.querySelector('#backHome').onclick=()=>{state.screen='home';render()}}});render();
